"""add shift availability to class

Revision ID: 3390ca40607c
Revises: c22e9c5a20bb
Create Date: 2025-04-07 14:14:49.784955

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3390ca40607c"
down_revision = "c22e9c5a20bb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("classes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "shift_availability", postgresql.ARRAY(sa.Integer()), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("classes", schema=None) as batch_op:
        batch_op.drop_column("shift_availability")

    # ### end Alembic commands ###
